FROM python:3.8.11-slim

ENV MLFLOW_VERSION=1.19
ENV MLFLOW_SERVER_ARTIFACT="wasbs://antonioblob@antoniostorage.blob.core.windows.net"
ENV AZURE_STORAGE_ACCESS_KEY=$AZURE_STORAGE_ACCESS_KEY

RUN pip install azure-storage-blob==12.8.1
RUN pip install mlflow[extras]==$MLFLOW_VERSION
EXPOSE 5000

ENTRYPOINT [ "/bin/bash", "-c", "exec mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ${MLFLOW_SERVER_ARTIFACT}"]