FROM python:3.8.11-slim

COPY . /
RUN pip install -r /requirements.txt
ENV AZURE_STORAGE_ACCESS_KEY=$AZURE_STORAGE_ACCESS_KEY

EXPOSE 8000

CMD ["uvicorn", "model_service:app", "--host", "0.0.0.0", "--port", "8000"]