name: test

on:
  pull_request:
    branches: [master]

jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build model image
        run: make build_model_image

      - name: Push model image to ACR
        run: make push_model_image_acr
        env:
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          CONT_REGISTRY_PW: ${{ secrets.CONT_REGISTRY_PW }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PW: ${{ secrets.AZURE_PW }}

      - name: Update image deployed in ACI
        run: make restart_model_acr

      - name: Tests model service
        run: python test/build_tests.py